name: "dsc_extractor"

on:
  push:
    branches:
      - main

jobs:
  compilation:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_16.0"
            runsOn: macos-14
            name: "macOS 14, Xcode 16.0, Swift 6.0"
          - xcode: "Xcode_15.4"
            runsOn: macos-14
            name: "macOS 14, Xcode 15.4, Swift 5.10"
          - xcode: "Xcode_15.2"
            runsOn: macos-13
            name: "macOS 14, Xcode 15.2, Swift 5.9.2"
          - xcode: "Xcode_15.1"
            runsOn: macOS-13
            name: "macOS 14, Xcode 15.1, Swift 5.9.1"
          - xcode: "Xcode_15.0"
            runsOn: macos-13
            name: "macOS 13, Xcode 15.0, Swift 5.9.0"
    steps:
      - uses: actions/checkout@v4
      - name: ${{ matrix.name }}
        run: make compile